/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    locations: Location;
    'daily-sets': DailySet;
    'practice-collections': PracticeCollection;
    'news-items': NewsItem;
    results: Result;
    groups: Group;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'daily-sets': DailySetsSelect<false> | DailySetsSelect<true>;
    'practice-collections': PracticeCollectionsSelect<false> | PracticeCollectionsSelect<true>;
    'news-items': NewsItemsSelect<false> | NewsItemsSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {};
  globalsSelect: {};
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * Admins can manage all content and reach /admin.
   */
  role: 'player' | 'admin';
  /**
   * ISO country code / emoji flag shown on the profile.
   */
  countryFlag?: string | null;
  prefs?: {
    tapAssist?: boolean | null;
    confirmTap?: boolean | null;
    showPreviousGuess?: boolean | null;
    scrollSensitivity?: number | null;
    useUtc?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * Source id from GeoNames (set by the importer; enables idempotent re-import).
   */
  geonameId?: number | null;
  /**
   * Population, used to derive difficulty and weight selection.
   */
  population?: number | null;
  country: string;
  /**
   * Latitude (-90 to 90)
   */
  lat: number;
  /**
   * Longitude (-180 to 180)
   */
  lng: number;
  difficulty: 'easy' | 'medium' | 'hard';
  tags?: ('capital' | 'city' | 'landmark' | 'unesco' | 'us-state' | 'waterway' | 'country')[] | null;
  /**
   * Optional image for picture-clue / flag modes.
   */
  image?: (number | null) | Media;
  /**
   * "This day in history" style blurbs revealed after a guess.
   */
  facts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-sets".
 */
export interface DailySet {
  id: number;
  /**
   * The UTC date this set is active. One set per day.
   */
  date: string;
  /**
   * Ordered rounds. Difficulty drives the score multiplier.
   */
  rounds: {
    location: number | Location;
    difficulty: 'easy' | 'medium' | 'hard';
    /**
     * The "on this day" event that picked this place, if any. Revealed post-guess.
     */
    event?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-collections".
 */
export interface PracticeCollection {
  id: number;
  title: string;
  /**
   * Short label, e.g. "Capitals", "Landmarks".
   */
  theme?: string | null;
  description?: string | null;
  locations: (number | Location)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items".
 */
export interface NewsItem {
  id: number;
  /**
   * Stable idempotency key, e.g. wp-onthisday:06-24:1789:<hash>.
   */
  sourceId: string;
  /**
   * Feed identifier, e.g. wikipedia-onthisday.
   */
  source: string;
  /**
   * MM-DD this event recurs on (UTC).
   */
  calendarDay: string;
  /**
   * Year the event occurred.
   */
  year?: number | null;
  /**
   * The event blurb, revealed post-guess as "On this day…".
   */
  text: string;
  /**
   * Optional source link.
   */
  link?: string | null;
  /**
   * Place names/coords we attempted to match against locations.
   */
  rawPlaceCandidates?:
    | {
        title: string;
        lat?: number | null;
        lng?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Locations resolved from this event at ingest time.
   */
  matchedLocations?: (number | Location)[] | null;
  fetchedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  /**
   * Null for a run completed while signed out.
   */
  user?: (number | null) | User;
  mode: 'daily' | 'speed' | 'versus' | 'history' | 'quiz';
  /**
   * UTC day (YYYY-MM-DD) for dated modes; empty otherwise.
   */
  dateKey?: string | null;
  title?: string | null;
  total: number;
  maxPossible?: number | null;
  /**
   * Per-round breakdown: name, base, multiplier, points, distanceKm.
   */
  rounds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Play time for timed modes.
   */
  elapsedMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  /**
   * URL identifier; generated from the name.
   */
  slug: string;
  owner: number | User;
  members?: (number | User)[] | null;
  /**
   * Share to invite; rotate to revoke old links.
   */
  inviteCode: string;
  visibility?: ('unlisted' | 'private') | null;
  /**
   * Optional emoji badge.
   */
  avatarEmoji?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'daily-sets';
        value: number | DailySet;
      } | null)
    | ({
        relationTo: 'practice-collections';
        value: number | PracticeCollection;
      } | null)
    | ({
        relationTo: 'news-items';
        value: number | NewsItem;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  countryFlag?: T;
  prefs?:
    | T
    | {
        tapAssist?: T;
        confirmTap?: T;
        showPreviousGuess?: T;
        scrollSensitivity?: T;
        useUtc?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  geonameId?: T;
  population?: T;
  country?: T;
  lat?: T;
  lng?: T;
  difficulty?: T;
  tags?: T;
  image?: T;
  facts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-sets_select".
 */
export interface DailySetsSelect<T extends boolean = true> {
  date?: T;
  rounds?:
    | T
    | {
        location?: T;
        difficulty?: T;
        event?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-collections_select".
 */
export interface PracticeCollectionsSelect<T extends boolean = true> {
  title?: T;
  theme?: T;
  description?: T;
  locations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items_select".
 */
export interface NewsItemsSelect<T extends boolean = true> {
  sourceId?: T;
  source?: T;
  calendarDay?: T;
  year?: T;
  text?: T;
  link?: T;
  rawPlaceCandidates?:
    | T
    | {
        title?: T;
        lat?: T;
        lng?: T;
        id?: T;
      };
  matchedLocations?: T;
  fetchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  user?: T;
  mode?: T;
  dateKey?: T;
  title?: T;
  total?: T;
  maxPossible?: T;
  rounds?: T;
  elapsedMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  owner?: T;
  members?: T;
  inviteCode?: T;
  visibility?: T;
  avatarEmoji?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}